#!/bin/bash

BASE_FOLDER="${BASE_FOLDER:-/tmp/upstream-boot-build/}"
BUILD_FOLDER=${BASE_FOLDER}/build
DEPLOY_FOLDER=${BASE_FOLDER}/deploy
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
LSDEFCONFIGS=`cd $SCRIPT_DIR/configs;ls|sort`
ARGS_DEFCONFIG=$*
DEFCONFIGS=${ARGS_DEFCONFIG:-$LSDEFCONFIGS}

build_config() {
	config=$1
	folder_name=`echo $config|sed -e "s/_defconfig//g"`
	build_path=$BUILD_FOLDER/$folder_name
	deploy_path=$DEPLOY_FOLDER/$folder_name
	make -j`nproc` O=$build_path D=$deploy_path mrproper
	make -j`nproc` O=$build_path D=$deploy_path $config
	make -j`nproc` O=$build_path D=$deploy_path
}

mkdir -p $BASE_FOLDER
make gitdesc 2>$BASE_FOLDER/git-revs.txt
for config in $DEFCONFIGS
do
	echo Building for "$config"
	# Wish we could run this in parallel, but k3imggen gets in the way
	build_config $config 2>&1 |tee $BASE_FOLDER/$config.txt
done

count=0
pass=0
fail=0
echo
echo "==> Attempt to summarize Error Logs:"
SUMMARY_FILE=$BASE_FOLDER/build-summary.txt
echo >$SUMMARY_FILE
for config in $DEFCONFIGS
do
	LOG=$BASE_FOLDER/$config.txt
	res=`tail -n 1 $LOG`
	success=`echo $res|grep 'BUILD COMPLETE:'`
	if [ x"$success" == x ]; then
		((fail++))
		echo "===> $config ($LOG) <===="
		result="FAIL"
		cat $LOG|grep -v removed|grep -v '^\s'|grep -v Leaving|grep -v Entering|grep -v '^#'
	else
		folder_name=`echo $config|sed -e "s/_defconfig//g"`
		((pass++))
		result="PASS: $DEPLOY_FOLDER/$folder_name"
	fi
	((count++))
	echo $config: $result>>$SUMMARY_FILE
done

echo
echo "==> Result of Builds:"
cat $SUMMARY_FILE

echo
echo
echo "==> All done: See $DEPLOY_FOLDER for files and $BUILD_FOLDER for build artifacts. $BASE_FOLDER for build logs"
echo "==> Summary of Builds: ($count builds: $pass Passed, $fail Failed)"

if [ $fail -gt 0 ]; then
	exit -1
fi
